spring.application.name=history-talk-backend
server.port=8080
spring.config.import=classpath:secretKey.properties

#config postgresql
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.schema=${DB_SCHEMA}
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
server.port=8080

# Config swagger

springdoc.api-docs.path=/api/v1/api-docs
springdoc.swagger-ui.path=/api/v1/swagger-ui
springdoc.swagger-ui.enabled=true
springdoc.enable-kotlin=false

