ALTER TABLE historical_schema."character" 
DROP COLUMN IF EXISTS born_date,
DROP COLUMN IF EXISTS death_date,
ADD COLUMN IF NOT EXISTS born_year INT,
ADD COLUMN IF NOT EXISTS born_month INT,
ADD COLUMN IF NOT EXISTS born_day INT,
ADD COLUMN IF NOT EXISTS is_born_bc BOOLEAN,
ADD COLUMN IF NOT EXISTS death_year INT,
ADD COLUMN IF NOT EXISTS death_month INT,
ADD COLUMN IF NOT EXISTS death_day INT,
ADD COLUMN IF NOT EXISTS is_death_bc BOOLEAN;

ALTER TABLE historical_schema.message
DROP COLUMN IF EXISTS role,
DROP COLUMN IF EXISTS side;